# Puerto donde correrá tu servidor (por defecto es 8080, pero puedes forzarlo aquí)
server.port=8080

# Conexión a tu clúster de MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://aaroncitto:microrent2026@cluster0.mongodb.net/microrent?retryWrites=true&w=majority